### ISSUE TITLE
Tip: How to load custom WAD

### ISSUE THREAD

**Issue by stefan-reich** [AXDOOMER/mochadoom#16]
I think this info could be useful for others too.

To play a custom WAD, e.g. square.wad from [here](https://redmars.org/wadc/examples/), first get e.g. plutonia.iawd from [here](https://github.com/dgeng/iwad).

Then use command line switches: -iwad plutonia.wad -file square.wad

[Example](http://code.botcompany.de/1025148) in my Java dialect.

**Comment by e1m1** [comment]
I can't comment on how the command line parameter is actually parsed but on first glance from enums already defined it looks like there is one for the -file arg:
https://github.com/AXDOOMER/mochadoom/blob/master/src/doom/CommandVariable.java

**Comment by stefan-reich** [comment]
@e1m1 Yes, thanks, got it to work now :)
