### ISSUE TITLE
Getting Java.lang.verifyerror

### ISSUE THREAD

**Issue by Sam-LearnsToCode** [AXDOOMER/mochadoom#26]
What jdk does it need to be compiled in for it to run properly ? 

I've tried 17 and it says verify error 
11 and 17 says it was compiled for a higher version (v60)

**Comment by AXDOOMER** [comment]
[v60 is Java 16. ](https://javaalmanac.io/bytecode/versions/)

There might be a version mismatch on your system, i.e. a different version of the JDK and JRE are installed. You should try uninstalling everything and install a single Java version. Mocha Doom should run fine on the latest Java version.

**Comment by AXDOOMER** [comment]
Were you able to fix the issue? I'm going to close this issue as I believe I identified the problem.
